version: '3'

services:
  database:
    image: 'postgres:14.1-alpine'
    ports:
      - '5432:5432'
    volumes:
       - nexus_server:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  nexus_server:
